version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ${DB_VOLUME}
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  pgadmin:
      container_name: pgadmin4_container2
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=root@admin.com
        - PGADMIN_DEFAULT_PASSWORD=root
      restart: always
      ports:
        - "5052:80"